name: "Node.js Vulnerabilities"
on: [push]
jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Install is-my-node-vulnerable
        run: npx is-my-node-vulnerable
      - uses: actions/checkout@v3
      - name: Check Node.js
        uses: nodejs/is-my-node-vulnerable@v1
        with:
          node-version: "18.14.1"