name: "Node.js Vulnerabilities"
on: [push]
jobs:
  is-my-node-vulnerable:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Install is-my-node-vulnerable
        run: npx is-my-node-vulnerable
      